### ISSUE TITLE
*.o: No such file or directory

### ISSUE THREAD

**Issue by SparoJ** [NativeScript/android-v8#18]
When i follow the md and build the v8 on macOS, i have this issue(as follow) ...

`
build finished in 1776 seconds
/Documents/2nd_Project/dev/android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/ar: creating ./dist//arm-release/libv8.a
/Documents/2nd_Project/dev/android-ndk-r20/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/arm-linux-androideabi/bin/ar: outgn/arm-release/obj/buildtools/third_party/libc++/libc++/*.o: No such file or directory
`
In the end i check the outgn dir and found mksnapshot under dist dir and no other items(.a static library) at all.
What did i missing? Thanks.

**Comment by darind** [comment]
We no longer maintain cross-compiling v8 on MacOS. We only use it to build the snapshot tools. You will need a Linux VM to cross-compile v8.

Thanks for pointing that out, we will update the readme to reflect it.

**Comment by SparoJ** [comment]
You mean if i want to follow this .md to build v8 successfully, i need to switch my OS to Linux... Alright thanks, i will try it on Linux Ubuntu VM...

**Comment by SparoJ** [comment]
I'm sorry i just want to ask another question for the build on MacOS, if you know any particular reason for this error [**clang: error: invalid linker name in argument '-fuse-ld=lld'**]:

`ninja -C out.gn/android.arm.release -j 4
ninja: Entering directory `out.gn/android.arm.release'
`[1/1] Regenerating ninja files
[1797/2499] LINK ./torque-language-server
FAILED: torque-language-server exe.unstripped/torque-language-server
python "../../build/toolchain/gcc_link_wrapper.py" --output="./torque-language-server" --strip="../../buildtools/third_party/eu-strip/bin/eu-strip" --unstripped-file="./exe.unstripped/torque-language-server" -- ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,--fatal-warnings -fPIC -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,-z,defs -Wl,--as-needed --gcc-toolchain=../../third_party/android_ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -Wl,--no-rosegment -Wl,--exclude-libs=libgcc.a -Wl,--exclude-libs=libvpx_assembly_arm.a --target=arm-linux-androideabi -Werror --sysroot=../../third_party/android_ndk/platforms/android-16/arch-arm -nostdlib -Wl,--warn-shared-textrel -pie -Bdynamic -Wl,-z,nocopyreloc -Wl,--warn-shared-textrel -Wl,-O2 -Wl,--gc-sections -L../../third_party/android_ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -o "./exe.unstripped/torque-language-server" -Wl,--start-group @"./torque-language-server.rsp"  -Wl,--end-group  ../../third_party/android_ndk/platforms/android-16/arch-arm/usr/lib/crtbegin_dynamic.o -landroid_support -lunwind ../../third_party/android_ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a -lc -ldl -lm -llog ../../third_party/android_ndk/platforms/android-16/arch-arm/usr/lib/crtend_android.o
clang: error: invalid linker name in argument '-fuse-ld=lld'
[1800/2499] CXX obj/v8_base_without_compiler/api.o
ninja: build stopped: subcommand failed.`

**Comment by darind** [comment]
I am afraid I haven't encountered this error but it looks like you might be using some outdated toolchain which is missing the LLD linker. What and how exactly are you trying to build? As I said earlier, cross-compiling v8 for android on MacOS is not supported.

**Comment by SparoJ** [comment]
Alright then, i just want to confirm that its impossible to build arm-v8 on
macOS not only follow this .md(
https://github.com/NativeScript/android-v8/blob/master/README.md)  but also
through the
official https://v8.dev/ guidelines...
That's what i am trying to do, after that i will try it on my linux Ubuntu
VMware and thanks for your patience.☺

Darin Dimitrov <notifications@github.com> 于2019年9月9日周一 上午12:17写道：

**Comment by darind** [comment]
We have updated the `build.sh` script so that only the `mksnapshot` tools are build on Mac OS.
