### ISSUE TITLE
Build Instructions?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/android-v8#2]
Are their any specific build instructions for it for the NativeScript versions; or do we just follow the Android building instructions @ googles site.     Which version of the Android runtimes are you building into the Android-runtimes?

These are the current valid v8 runtimes:
android_ia32 
android_x64 
android_arm 
android_arm64
android_mipsel
android_x87

I assume it is ia32 & arm? 
Any specific flags?

**Comment by slavchev** [comment]
Hi @NathanaelA 

I changed a bit the repo organization and now each branch provides build instructions. The `master` branch contains just a README.md with a link to the latest branch.
