### ISSUE TITLE
 undefined reference to 'v8::platform::NewDefaultPlatform

### ISSUE THREAD

**Issue by guzhonL** [NativeScript/android-v8#20]
I followed the README.md and build v8 successfully on linux, But when i added libv8.a and  all the needed header to my own project, i have this issue(as follow):

 JNI_OnLoad: error: undefined reference to 'v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::__ndkCr::unique_ptr<v8::TracingController, std::__ndkCr::default_delete<v8::TracingController> >)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by darind** [comment]
You can try searching the exported symbols from the static library using `nm`:

```
nm -gAC libv8.a | grep "v8::platform::NewDefaultPlatform"
```

Normally you should see the following output:

```
libv8.a:default-platform.o:0000000000000000 T v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::__Cr::unique_ptr<v8::TracingController, std::__Cr::default_delete<v8::TracingController> >)
```

As you can see there are some different namespaces used in this build:

```
std::__Cr::unique_ptr
```

instead of

```
std::__ndkCr::unique_ptr
```

The error message seems to indicate that you are not using the custom libc++ in your project that was used during the v8 build. So make sure that you link against this custom STL in order to successfully compile. You can take a look at how this is achieved in the android runtime [CMakeLists.txt](https://github.com/NativeScript/android-runtime/blob/master/test-app/runtime/CMakeLists.txt)

**Comment by guzhonL** [comment]
Thanks very very very much for replying!!!
I copied v8/buildtools/third_party/libc++/trunk/include (libc++) into my own project, and added libc++ to CMakeLists.txt as android-runtime project does. But there is another problem:

_error: unknown type name 'uint8_t'  typedef uint8_t  jboolean; /* unsigned 8 bits */
error: unknown type name 'int8_t'  typedef int8_t   jbyte;    /* signed 8 bits */_

i included jni.h in my code already.It seems that stdint.h included from jni.h doesn't work!

**Comment by darind** [comment]
Make sure you are using the latest NDK r20.

**Comment by guzhonL** [comment]
Thanks a lot!!
But i still have problems even  used the latest NDK r20.it was only building failed for 'armeabi-v7a' but 'arm64-v8a' was ok;
the failed info as follows:

/src/main/libs/armeabi-v7a/libv8.a(locale.o):locale.cpp:function std::__Cr::ctype_byname<wchar_t>::do_is(unsigned long, wchar_t) const: error: undefined reference to 'iswblank'
/src/main/libs/armeabi-v7a/libv8.a(locale.o):locale.cpp:function std::__Cr::ctype_byname<wchar_t>::do_is(wchar_t const*, wchar_t const*, unsigned long*) const: error: undefined reference to 'iswblank'/src/main/libs/armeabi-v7a/libv8.a(locale.o):locale.cpp:function std::__Cr::__libcpp_mb_cur_max_l(__locale_t*): error: undefined reference to '__ctype_get_mb_cur_max'
/src/main/libs/armeabi-v7a/libv8.a(locale.o):locale.cpp:function std::__Cr::__libcpp_mb_cur_max_l(__locale_t*): error: undefined reference to '__ctype_get_mb_cur_max'

**Comment by darind** [comment]
Did you link your project against `libandroid_support.a`? This is necessary only when building for `armeabi-v7a` or `x86`. The 64 bit flavours do not require this static library.

**Comment by guzhonL** [comment]
I definitely linked my project against 'libandroid_support.a'. And I try building my project with libv8.a downloaded from android-runtime project, it build successfully. 

nm -gAC libv8.a | grep "iswblank"
when run this commond with my own libv8.a, the output as follows:
libv8.a:locale.o:          U iswblank
but it output nothing with the downloaded libv8.a from android-runtime project

**Comment by darind** [comment]
Could you send a repro repository so that I can take a look?

**Comment by guzhonL** [comment]
I rebuild libv8.a with the latest NDK r20 and the problem has gone. Thanks!!

**Comment by marklove5102** [comment]
> Could you send a repro repository so that I can take a look?

I can reproduce this problem under linux using libv8.so
