### ISSUE TITLE
5.1.xtimeline?

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/android-v8#3]
@jasssonpet - are we really thinking of jumping to the Canary v8 Engine?   I'm all for running bleeding edge; but I can't imagine that running canary for my released application as this is the least tested versions of the v8's  and if you are going to run canary; why are we picking .150 instead of 300ish you are missing about 150 potential fixes (& new bugs <G>).  

So I guess the question is what is the time line for this engine being released for android; or are you going to wait until 5.1 gets moved into the beta channel and then upgrade to the current 5.1 at that point?

**Comment by jasssonpet** [comment]
Hey @NathanaelA,

Thanks for noticing the new V8 branch here. This is only an experimental branch to try out the new V8 APIs related to the snapshots (most notably [this commit](https://github.com/NativeScript/android-v8/commit/f507bc1c7242d338b04d6bba5ea78cbb42cf0e13)) so we know what to expect in the future. I can assure you, that in no way are we going to use non-stable V8 builds in production.

Regarding your question about V8 upgrades in the Android Runtime I'm afraid I can't answer you. Maybe @slavchev has more information about this.

**Comment by slavchev** [comment]
@NathanaelA The process we followed so far is when we decide to upgrade V8 we use the current at that time V8 version used by Chrome (stable). For example, if we decide to upgrade V8 today we would use `4.9.385.35` as it is today's current version. It is a bit conservative approach but so far it works for us. Also, we keep an eye at what is going with V8 and there is nothing stopping us from using the latest V8 build. Maybe we will adopt more aggressive upgrade policy. I guess it is a matter of providing infrastructure for automatic building and testing.

**Comment by NathanaelA** [comment]
:+1:  Thanks guys for the info.  I was really hoping 5.1 was just a test branch for snapshotting; its pretty nice that you already have your code working with 5.1 already though!

  @slavchev that policy actually does sound like the best policy to use the current release chrome version, that would be the most tested version.  :-)
